# Generated by Django 4.1.5 on 2023-02-05 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('C_name', models.CharField(max_length=255)),
                ('C_description', models.TextField()),
                ('C_image', models.ImageField(upload_to='static/image')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('F_name', models.CharField(max_length=255)),
                ('F_Email', models.EmailField(max_length=254)),
                ('F_mobile', models.CharField(max_length=20)),
                ('F_text', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('P_name', models.CharField(max_length=255)),
                ('P_descriptions', models.TextField()),
                ('P_image', models.ImageField(upload_to='static/images')),
            ],
        ),
    ]
